/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AreaRouteImport } from './routes/area'
import { Route as ApartmentRouteImport } from './routes/apartment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaRestaurantsRouteImport } from './routes/area.restaurants'
import { Route as AreaEntertainmentRouteImport } from './routes/area.entertainment'
import { Route as AreaBeachesRouteImport } from './routes/area.beaches'
import { Route as AreaAttractionsRouteImport } from './routes/area.attractions'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentRoute = ApartmentRouteImport.update({
  id: '/apartment',
  path: '/apartment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRestaurantsRoute = AreaRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AreaRoute,
} as any)
const AreaEntertainmentRoute = AreaEntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => AreaRoute,
} as any)
const AreaBeachesRoute = AreaBeachesRouteImport.update({
  id: '/beaches',
  path: '/beaches',
  getParentRoute: () => AreaRoute,
} as any)
const AreaAttractionsRoute = AreaAttractionsRouteImport.update({
  id: '/attractions',
  path: '/attractions',
  getParentRoute: () => AreaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apartment': typeof ApartmentRoute
  '/area': typeof AreaRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/area/attractions': typeof AreaAttractionsRoute
  '/area/beaches': typeof AreaBeachesRoute
  '/area/entertainment': typeof AreaEntertainmentRoute
  '/area/restaurants': typeof AreaRestaurantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apartment': typeof ApartmentRoute
  '/area': typeof AreaRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/area/attractions': typeof AreaAttractionsRoute
  '/area/beaches': typeof AreaBeachesRoute
  '/area/entertainment': typeof AreaEntertainmentRoute
  '/area/restaurants': typeof AreaRestaurantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apartment': typeof ApartmentRoute
  '/area': typeof AreaRouteWithChildren
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/area/attractions': typeof AreaAttractionsRoute
  '/area/beaches': typeof AreaBeachesRoute
  '/area/entertainment': typeof AreaEntertainmentRoute
  '/area/restaurants': typeof AreaRestaurantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apartment'
    | '/area'
    | '/contact'
    | '/sitemap.xml'
    | '/area/attractions'
    | '/area/beaches'
    | '/area/entertainment'
    | '/area/restaurants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apartment'
    | '/area'
    | '/contact'
    | '/sitemap.xml'
    | '/area/attractions'
    | '/area/beaches'
    | '/area/entertainment'
    | '/area/restaurants'
  id:
    | '__root__'
    | '/'
    | '/apartment'
    | '/area'
    | '/contact'
    | '/sitemap.xml'
    | '/area/attractions'
    | '/area/beaches'
    | '/area/entertainment'
    | '/area/restaurants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApartmentRoute: typeof ApartmentRoute
  AreaRoute: typeof AreaRouteWithChildren
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartment': {
      id: '/apartment'
      path: '/apartment'
      fullPath: '/apartment'
      preLoaderRoute: typeof ApartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area/restaurants': {
      id: '/area/restaurants'
      path: '/restaurants'
      fullPath: '/area/restaurants'
      preLoaderRoute: typeof AreaRestaurantsRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/entertainment': {
      id: '/area/entertainment'
      path: '/entertainment'
      fullPath: '/area/entertainment'
      preLoaderRoute: typeof AreaEntertainmentRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/beaches': {
      id: '/area/beaches'
      path: '/beaches'
      fullPath: '/area/beaches'
      preLoaderRoute: typeof AreaBeachesRouteImport
      parentRoute: typeof AreaRoute
    }
    '/area/attractions': {
      id: '/area/attractions'
      path: '/attractions'
      fullPath: '/area/attractions'
      preLoaderRoute: typeof AreaAttractionsRouteImport
      parentRoute: typeof AreaRoute
    }
  }
}

interface AreaRouteChildren {
  AreaAttractionsRoute: typeof AreaAttractionsRoute
  AreaBeachesRoute: typeof AreaBeachesRoute
  AreaEntertainmentRoute: typeof AreaEntertainmentRoute
  AreaRestaurantsRoute: typeof AreaRestaurantsRoute
}

const AreaRouteChildren: AreaRouteChildren = {
  AreaAttractionsRoute: AreaAttractionsRoute,
  AreaBeachesRoute: AreaBeachesRoute,
  AreaEntertainmentRoute: AreaEntertainmentRoute,
  AreaRestaurantsRoute: AreaRestaurantsRoute,
}

const AreaRouteWithChildren = AreaRoute._addFileChildren(AreaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApartmentRoute: ApartmentRoute,
  AreaRoute: AreaRouteWithChildren,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
